# Generated by Django 2.2.7 on 2019-11-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuscaFavorita',
        ),
    ]
