# Generated by Django 2.2.6 on 2019-12-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motos', '0003_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritos',
            name='anoModelo',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='favoritos',
            name='ano_modelo',
            field=models.CharField(blank=True, db_column='ano_modelo', max_length=50),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='id_usuario',
            field=models.IntegerField(blank=True, db_column='id_usuario', default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritos',
            name='montadora',
            field=models.CharField(blank=True, db_column='montadora', max_length=50),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='modelo',
            field=models.CharField(blank=True, db_column='modelo', max_length=50),
        ),
    ]
